2023-08-12 22:52:09,714:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-12 22:52:09,714:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-12 22:52:09,714:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-12 22:52:09,714:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-12 22:53:16,515:INFO:PyCaret ClassificationExperiment
2023-08-12 22:53:16,516:INFO:Logging name: clf-default-name
2023-08-12 22:53:16,516:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-12 22:53:16,516:INFO:version 3.0.4
2023-08-12 22:53:16,516:INFO:Initializing setup()
2023-08-12 22:53:16,516:INFO:self.USI: a485
2023-08-12 22:53:16,516:INFO:self._variable_keys: {'USI', 'html_param', 'memory', 'exp_name_log', 'idx', 'fold_groups_param', '_ml_usecase', 'X_test', 'y', 'target_param', 'X', 'fold_generator', 'seed', 'y_train', 'data', 'exp_id', 'is_multiclass', 'logging_param', '_available_plots', 'gpu_param', 'y_test', 'gpu_n_jobs_param', 'log_plots_param', 'pipeline', 'fold_shuffle_param', 'fix_imbalance', 'X_train', 'n_jobs_param'}
2023-08-12 22:53:16,516:INFO:Checking environment
2023-08-12 22:53:16,516:INFO:python_version: 3.10.9
2023-08-12 22:53:16,517:INFO:python_build: ('main', 'Mar  1 2023 18:18:15')
2023-08-12 22:53:16,517:INFO:machine: AMD64
2023-08-12 22:53:16,517:INFO:platform: Windows-10-10.0.22621-SP0
2023-08-12 22:53:16,517:INFO:Memory: svmem(total=8299257856, available=1528610816, percent=81.6, used=6770647040, free=1528610816)
2023-08-12 22:53:16,517:INFO:Physical Core: 4
2023-08-12 22:53:16,518:INFO:Logical Core: 8
2023-08-12 22:53:16,518:INFO:Checking libraries
2023-08-12 22:53:16,518:INFO:System:
2023-08-12 22:53:16,518:INFO:    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
2023-08-12 22:53:16,518:INFO:executable: C:\Users\hites\anaconda3\python.exe
2023-08-12 22:53:16,518:INFO:   machine: Windows-10-10.0.22621-SP0
2023-08-12 22:53:16,518:INFO:PyCaret required dependencies:
2023-08-12 22:53:18,593:INFO:                 pip: 22.3.1
2023-08-12 22:53:18,593:INFO:          setuptools: 65.6.3
2023-08-12 22:53:18,593:INFO:             pycaret: 3.0.4
2023-08-12 22:53:18,593:INFO:             IPython: 7.34.0
2023-08-12 22:53:18,593:INFO:          ipywidgets: 7.6.5
2023-08-12 22:53:18,593:INFO:                tqdm: 4.64.1
2023-08-12 22:53:18,593:INFO:               numpy: 1.23.5
2023-08-12 22:53:18,593:INFO:              pandas: 1.5.3
2023-08-12 22:53:18,593:INFO:              jinja2: 3.1.2
2023-08-12 22:53:18,593:INFO:               scipy: 1.10.0
2023-08-12 22:53:18,593:INFO:              joblib: 1.3.2
2023-08-12 22:53:18,593:INFO:             sklearn: 1.2.1
2023-08-12 22:53:18,594:INFO:                pyod: 1.1.0
2023-08-12 22:53:18,594:INFO:            imblearn: 0.10.1
2023-08-12 22:53:18,594:INFO:   category_encoders: 2.6.1
2023-08-12 22:53:18,594:INFO:            lightgbm: 4.0.0
2023-08-12 22:53:18,594:INFO:               numba: 0.56.4
2023-08-12 22:53:18,594:INFO:            requests: 2.28.1
2023-08-12 22:53:18,594:INFO:          matplotlib: 3.7.0
2023-08-12 22:53:18,594:INFO:          scikitplot: 0.3.7
2023-08-12 22:53:18,594:INFO:         yellowbrick: 1.5
2023-08-12 22:53:18,594:INFO:              plotly: 5.16.0
2023-08-12 22:53:18,594:INFO:    plotly-resampler: Not installed
2023-08-12 22:53:18,594:INFO:             kaleido: 0.2.1
2023-08-12 22:53:18,594:INFO:           schemdraw: 0.15
2023-08-12 22:53:18,594:INFO:         statsmodels: 0.13.5
2023-08-12 22:53:18,594:INFO:              sktime: 0.21.0
2023-08-12 22:53:18,594:INFO:               tbats: 1.1.3
2023-08-12 22:53:18,594:INFO:            pmdarima: 2.0.3
2023-08-12 22:53:18,594:INFO:              psutil: 5.9.0
2023-08-12 22:53:18,594:INFO:          markupsafe: 2.1.1
2023-08-12 22:53:18,595:INFO:             pickle5: Not installed
2023-08-12 22:53:18,595:INFO:         cloudpickle: 2.0.0
2023-08-12 22:53:18,595:INFO:         deprecation: 2.1.0
2023-08-12 22:53:18,595:INFO:              xxhash: 3.3.0
2023-08-12 22:53:18,595:INFO:           wurlitzer: Not installed
2023-08-12 22:53:18,595:INFO:PyCaret optional dependencies:
2023-08-12 22:53:19,491:WARNING:C:\Users\hites\anaconda3\lib\site-packages\trio\_core\_multierror.py:412: RuntimeWarning:

IPython detected, but you already have a custom exception handler installed. I'll skip installing Trio's custom handler, but this means exception groups will not show full tracebacks.


2023-08-12 22:53:26,715:INFO:                shap: 0.42.1
2023-08-12 22:53:26,715:INFO:           interpret: 0.4.3
2023-08-12 22:53:26,715:INFO:                umap: 0.5.3
2023-08-12 22:53:26,715:INFO:    pandas_profiling: 4.5.1
2023-08-12 22:53:26,715:INFO:  explainerdashboard: 0.4.3
2023-08-12 22:53:26,716:INFO:             autoviz: 0.1.730
2023-08-12 22:53:26,716:INFO:           fairlearn: 0.7.0
2023-08-12 22:53:26,716:INFO:          deepchecks: 0.17.4
2023-08-12 22:53:26,716:INFO:             xgboost: 1.7.6
2023-08-12 22:53:26,716:INFO:            catboost: 1.2
2023-08-12 22:53:26,716:INFO:              kmodes: 0.12.2
2023-08-12 22:53:26,716:INFO:             mlxtend: 0.22.0
2023-08-12 22:53:26,716:INFO:       statsforecast: 1.5.0
2023-08-12 22:53:26,716:INFO:        tune_sklearn: 0.4.6
2023-08-12 22:53:26,716:INFO:                 ray: 2.6.2
2023-08-12 22:53:26,716:INFO:            hyperopt: 0.2.7
2023-08-12 22:53:26,717:INFO:              optuna: 3.3.0
2023-08-12 22:53:26,717:INFO:               skopt: 0.9.0
2023-08-12 22:53:26,717:INFO:              mlflow: 1.30.1
2023-08-12 22:53:26,717:INFO:              gradio: 3.40.1
2023-08-12 22:53:26,717:INFO:             fastapi: 0.101.0
2023-08-12 22:53:26,717:INFO:             uvicorn: 0.23.2
2023-08-12 22:53:26,717:INFO:              m2cgen: 0.10.0
2023-08-12 22:53:26,717:INFO:           evidently: 0.2.8
2023-08-12 22:53:26,717:INFO:               fugue: 0.8.6
2023-08-12 22:53:26,717:INFO:           streamlit: Not installed
2023-08-12 22:53:26,717:INFO:             prophet: Not installed
2023-08-12 22:53:26,717:INFO:None
2023-08-12 22:53:26,718:INFO:Set up data.
2023-08-12 22:53:26,732:INFO:Set up train/test split.
2023-08-12 22:53:26,749:INFO:Set up index.
2023-08-12 22:53:26,751:INFO:Set up folding strategy.
2023-08-12 22:53:26,751:INFO:Assigning column types.
2023-08-12 22:53:26,762:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-12 22:53:26,839:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-12 22:53:26,843:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-12 22:53:26,897:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:30,031:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:35,282:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-12 22:53:35,283:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-12 22:53:35,324:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:35,327:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:35,328:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-08-12 22:53:35,389:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-12 22:53:35,428:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:35,433:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:35,504:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-12 22:53:35,537:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:35,541:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:35,542:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-08-12 22:53:35,630:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:35,633:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:35,704:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:35,707:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:35,721:INFO:Preparing preprocessing pipeline...
2023-08-12 22:53:35,724:INFO:Set up simple imputation.
2023-08-12 22:53:35,757:INFO:Finished creating preprocessing pipeline.
2023-08-12 22:53:35,764:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\hites\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['ph', 'Hardness', 'Solids',
                                             'Chloramines', 'Sulfate',
                                             'Conductivity', 'Organic_carbon',
                                             'Trihalomethanes', 'Turbidity'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-08-12 22:53:35,764:INFO:Creating final display dataframe.
2023-08-12 22:53:35,857:INFO:Setup _display_container:                     Description             Value
0                    Session id               786
1                        Target        Potability
2                   Target type            Binary
3           Original data shape        (3276, 10)
4        Transformed data shape        (3276, 10)
5   Transformed train set shape        (2293, 10)
6    Transformed test set shape         (983, 10)
7              Numeric features                 9
8      Rows with missing values              4.9%
9                    Preprocess              True
10              Imputation type            simple
11           Numeric imputation              mean
12       Categorical imputation              mode
13               Fold Generator   StratifiedKFold
14                  Fold Number                10
15                     CPU Jobs                -1
16                      Use GPU             False
17               Log Experiment             False
18              Experiment Name  clf-default-name
19                          USI              a485
2023-08-12 22:53:35,953:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:35,959:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:36,053:INFO:Soft dependency imported: xgboost: 1.7.6
2023-08-12 22:53:36,056:INFO:Soft dependency imported: catboost: 1.2
2023-08-12 22:53:36,057:INFO:setup() successfully completed in 19.54s...............
2023-08-12 22:53:36,057:INFO:Initializing compare_models()
2023-08-12 22:53:36,057:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-08-12 22:53:36,057:INFO:Checking exceptions
2023-08-12 22:53:36,071:INFO:Preparing display monitor
2023-08-12 22:53:36,114:INFO:Initializing Logistic Regression
2023-08-12 22:53:36,115:INFO:Total runtime is 1.7249584197998046e-05 minutes
2023-08-12 22:53:36,120:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:36,121:INFO:Initializing create_model()
2023-08-12 22:53:36,121:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:36,121:INFO:Checking exceptions
2023-08-12 22:53:36,121:INFO:Importing libraries
2023-08-12 22:53:36,121:INFO:Copying training dataset
2023-08-12 22:53:36,126:INFO:Defining folds
2023-08-12 22:53:36,126:INFO:Declaring metric variables
2023-08-12 22:53:36,130:INFO:Importing untrained model
2023-08-12 22:53:36,134:INFO:Logistic Regression Imported successfully
2023-08-12 22:53:36,142:INFO:Starting cross validation
2023-08-12 22:53:36,143:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:46,606:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,607:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,608:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,608:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,608:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,619:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,951:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,964:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:46,969:INFO:Calculating mean and std
2023-08-12 22:53:46,971:INFO:Creating metrics dataframe
2023-08-12 22:53:46,981:INFO:Uploading results into container
2023-08-12 22:53:46,982:INFO:Uploading model into container now
2023-08-12 22:53:46,983:INFO:_master_model_container: 1
2023-08-12 22:53:46,983:INFO:_display_container: 2
2023-08-12 22:53:46,983:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=786, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-12 22:53:46,983:INFO:create_model() successfully completed......................................
2023-08-12 22:53:47,487:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:47,488:INFO:Creating metrics dataframe
2023-08-12 22:53:47,502:INFO:Initializing K Neighbors Classifier
2023-08-12 22:53:47,502:INFO:Total runtime is 0.18980722427368163 minutes
2023-08-12 22:53:47,506:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:47,507:INFO:Initializing create_model()
2023-08-12 22:53:47,507:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:47,507:INFO:Checking exceptions
2023-08-12 22:53:47,507:INFO:Importing libraries
2023-08-12 22:53:47,507:INFO:Copying training dataset
2023-08-12 22:53:47,512:INFO:Defining folds
2023-08-12 22:53:47,512:INFO:Declaring metric variables
2023-08-12 22:53:47,516:INFO:Importing untrained model
2023-08-12 22:53:47,520:INFO:K Neighbors Classifier Imported successfully
2023-08-12 22:53:47,532:INFO:Starting cross validation
2023-08-12 22:53:47,533:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:47,894:INFO:Calculating mean and std
2023-08-12 22:53:47,896:INFO:Creating metrics dataframe
2023-08-12 22:53:47,905:INFO:Uploading results into container
2023-08-12 22:53:47,907:INFO:Uploading model into container now
2023-08-12 22:53:47,908:INFO:_master_model_container: 2
2023-08-12 22:53:47,908:INFO:_display_container: 2
2023-08-12 22:53:47,909:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-08-12 22:53:47,909:INFO:create_model() successfully completed......................................
2023-08-12 22:53:48,410:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:48,410:INFO:Creating metrics dataframe
2023-08-12 22:53:48,432:INFO:Initializing Naive Bayes
2023-08-12 22:53:48,432:INFO:Total runtime is 0.2053032875061035 minutes
2023-08-12 22:53:48,440:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:48,441:INFO:Initializing create_model()
2023-08-12 22:53:48,441:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:48,441:INFO:Checking exceptions
2023-08-12 22:53:48,441:INFO:Importing libraries
2023-08-12 22:53:48,441:INFO:Copying training dataset
2023-08-12 22:53:48,450:INFO:Defining folds
2023-08-12 22:53:48,450:INFO:Declaring metric variables
2023-08-12 22:53:48,456:INFO:Importing untrained model
2023-08-12 22:53:48,462:INFO:Naive Bayes Imported successfully
2023-08-12 22:53:48,476:INFO:Starting cross validation
2023-08-12 22:53:48,477:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:48,678:INFO:Calculating mean and std
2023-08-12 22:53:48,680:INFO:Creating metrics dataframe
2023-08-12 22:53:48,688:INFO:Uploading results into container
2023-08-12 22:53:48,689:INFO:Uploading model into container now
2023-08-12 22:53:48,690:INFO:_master_model_container: 3
2023-08-12 22:53:48,690:INFO:_display_container: 2
2023-08-12 22:53:48,691:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-08-12 22:53:48,691:INFO:create_model() successfully completed......................................
2023-08-12 22:53:49,186:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:49,186:INFO:Creating metrics dataframe
2023-08-12 22:53:49,197:INFO:Initializing Decision Tree Classifier
2023-08-12 22:53:49,198:INFO:Total runtime is 0.21807156403859454 minutes
2023-08-12 22:53:49,201:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:49,202:INFO:Initializing create_model()
2023-08-12 22:53:49,202:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:49,202:INFO:Checking exceptions
2023-08-12 22:53:49,202:INFO:Importing libraries
2023-08-12 22:53:49,202:INFO:Copying training dataset
2023-08-12 22:53:49,207:INFO:Defining folds
2023-08-12 22:53:49,207:INFO:Declaring metric variables
2023-08-12 22:53:49,211:INFO:Importing untrained model
2023-08-12 22:53:49,216:INFO:Decision Tree Classifier Imported successfully
2023-08-12 22:53:49,225:INFO:Starting cross validation
2023-08-12 22:53:49,227:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:49,523:INFO:Calculating mean and std
2023-08-12 22:53:49,525:INFO:Creating metrics dataframe
2023-08-12 22:53:49,531:INFO:Uploading results into container
2023-08-12 22:53:49,532:INFO:Uploading model into container now
2023-08-12 22:53:49,532:INFO:_master_model_container: 4
2023-08-12 22:53:49,532:INFO:_display_container: 2
2023-08-12 22:53:49,533:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=786, splitter='best')
2023-08-12 22:53:49,533:INFO:create_model() successfully completed......................................
2023-08-12 22:53:50,008:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:50,009:INFO:Creating metrics dataframe
2023-08-12 22:53:50,044:INFO:Initializing SVM - Linear Kernel
2023-08-12 22:53:50,044:INFO:Total runtime is 0.23217240174611406 minutes
2023-08-12 22:53:50,052:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:50,053:INFO:Initializing create_model()
2023-08-12 22:53:50,053:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:50,053:INFO:Checking exceptions
2023-08-12 22:53:50,053:INFO:Importing libraries
2023-08-12 22:53:50,053:INFO:Copying training dataset
2023-08-12 22:53:50,063:INFO:Defining folds
2023-08-12 22:53:50,064:INFO:Declaring metric variables
2023-08-12 22:53:50,073:INFO:Importing untrained model
2023-08-12 22:53:50,079:INFO:SVM - Linear Kernel Imported successfully
2023-08-12 22:53:50,107:INFO:Starting cross validation
2023-08-12 22:53:50,111:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:50,231:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,237:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,238:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,243:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,249:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,255:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,256:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:50,258:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,260:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:50,263:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:50,277:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,281:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:50,297:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,301:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:50,307:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-12 22:53:50,328:INFO:Calculating mean and std
2023-08-12 22:53:50,329:INFO:Creating metrics dataframe
2023-08-12 22:53:50,334:INFO:Uploading results into container
2023-08-12 22:53:50,334:INFO:Uploading model into container now
2023-08-12 22:53:50,335:INFO:_master_model_container: 5
2023-08-12 22:53:50,335:INFO:_display_container: 2
2023-08-12 22:53:50,336:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=786, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-08-12 22:53:50,336:INFO:create_model() successfully completed......................................
2023-08-12 22:53:50,850:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:50,850:INFO:Creating metrics dataframe
2023-08-12 22:53:50,864:INFO:Initializing Ridge Classifier
2023-08-12 22:53:50,864:INFO:Total runtime is 0.24583600759506222 minutes
2023-08-12 22:53:50,868:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:50,869:INFO:Initializing create_model()
2023-08-12 22:53:50,869:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:50,869:INFO:Checking exceptions
2023-08-12 22:53:50,869:INFO:Importing libraries
2023-08-12 22:53:50,869:INFO:Copying training dataset
2023-08-12 22:53:50,873:INFO:Defining folds
2023-08-12 22:53:50,873:INFO:Declaring metric variables
2023-08-12 22:53:50,877:INFO:Importing untrained model
2023-08-12 22:53:50,880:INFO:Ridge Classifier Imported successfully
2023-08-12 22:53:50,889:INFO:Starting cross validation
2023-08-12 22:53:50,891:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.60691e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.58577e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.6268e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.49713e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.5576e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.65321e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,001:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.5598e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,026:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,026:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,028:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,028:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,030:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,034:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,034:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,035:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,038:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:51,041:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:51,047:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:51,080:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.52927e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,089:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=7.44412e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2023-08-12 22:53:51,101:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,106:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:51,110:WARNING:C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-12 22:53:51,114:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:53:51,134:INFO:Calculating mean and std
2023-08-12 22:53:51,136:INFO:Creating metrics dataframe
2023-08-12 22:53:51,143:INFO:Uploading results into container
2023-08-12 22:53:51,144:INFO:Uploading model into container now
2023-08-12 22:53:51,145:INFO:_master_model_container: 6
2023-08-12 22:53:51,145:INFO:_display_container: 2
2023-08-12 22:53:51,146:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=786, solver='auto',
                tol=0.0001)
2023-08-12 22:53:51,146:INFO:create_model() successfully completed......................................
2023-08-12 22:53:51,571:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:51,571:INFO:Creating metrics dataframe
2023-08-12 22:53:51,594:INFO:Initializing Random Forest Classifier
2023-08-12 22:53:51,594:INFO:Total runtime is 0.25800568262736 minutes
2023-08-12 22:53:51,600:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:51,601:INFO:Initializing create_model()
2023-08-12 22:53:51,601:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:51,601:INFO:Checking exceptions
2023-08-12 22:53:51,601:INFO:Importing libraries
2023-08-12 22:53:51,601:INFO:Copying training dataset
2023-08-12 22:53:51,609:INFO:Defining folds
2023-08-12 22:53:51,609:INFO:Declaring metric variables
2023-08-12 22:53:51,615:INFO:Importing untrained model
2023-08-12 22:53:51,622:INFO:Random Forest Classifier Imported successfully
2023-08-12 22:53:51,638:INFO:Starting cross validation
2023-08-12 22:53:51,640:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:54,588:INFO:Calculating mean and std
2023-08-12 22:53:54,589:INFO:Creating metrics dataframe
2023-08-12 22:53:54,606:INFO:Uploading results into container
2023-08-12 22:53:54,609:INFO:Uploading model into container now
2023-08-12 22:53:54,610:INFO:_master_model_container: 7
2023-08-12 22:53:54,610:INFO:_display_container: 2
2023-08-12 22:53:54,611:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=786, verbose=0, warm_start=False)
2023-08-12 22:53:54,611:INFO:create_model() successfully completed......................................
2023-08-12 22:53:55,070:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:55,070:INFO:Creating metrics dataframe
2023-08-12 22:53:55,099:INFO:Initializing Quadratic Discriminant Analysis
2023-08-12 22:53:55,100:INFO:Total runtime is 0.3164391795794169 minutes
2023-08-12 22:53:55,107:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:55,107:INFO:Initializing create_model()
2023-08-12 22:53:55,108:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:55,108:INFO:Checking exceptions
2023-08-12 22:53:55,108:INFO:Importing libraries
2023-08-12 22:53:55,108:INFO:Copying training dataset
2023-08-12 22:53:55,116:INFO:Defining folds
2023-08-12 22:53:55,116:INFO:Declaring metric variables
2023-08-12 22:53:55,127:INFO:Importing untrained model
2023-08-12 22:53:55,135:INFO:Quadratic Discriminant Analysis Imported successfully
2023-08-12 22:53:55,150:INFO:Starting cross validation
2023-08-12 22:53:55,151:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:55,441:INFO:Calculating mean and std
2023-08-12 22:53:55,442:INFO:Creating metrics dataframe
2023-08-12 22:53:55,453:INFO:Uploading results into container
2023-08-12 22:53:55,455:INFO:Uploading model into container now
2023-08-12 22:53:55,455:INFO:_master_model_container: 8
2023-08-12 22:53:55,455:INFO:_display_container: 2
2023-08-12 22:53:55,456:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-08-12 22:53:55,456:INFO:create_model() successfully completed......................................
2023-08-12 22:53:55,953:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:55,953:INFO:Creating metrics dataframe
2023-08-12 22:53:55,980:INFO:Initializing Ada Boost Classifier
2023-08-12 22:53:55,980:INFO:Total runtime is 0.3311112443606059 minutes
2023-08-12 22:53:55,985:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:55,986:INFO:Initializing create_model()
2023-08-12 22:53:55,986:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:55,986:INFO:Checking exceptions
2023-08-12 22:53:55,986:INFO:Importing libraries
2023-08-12 22:53:55,986:INFO:Copying training dataset
2023-08-12 22:53:55,991:INFO:Defining folds
2023-08-12 22:53:55,992:INFO:Declaring metric variables
2023-08-12 22:53:55,998:INFO:Importing untrained model
2023-08-12 22:53:56,009:INFO:Ada Boost Classifier Imported successfully
2023-08-12 22:53:56,030:INFO:Starting cross validation
2023-08-12 22:53:56,034:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:53:57,467:INFO:Calculating mean and std
2023-08-12 22:53:57,468:INFO:Creating metrics dataframe
2023-08-12 22:53:57,486:INFO:Uploading results into container
2023-08-12 22:53:57,489:INFO:Uploading model into container now
2023-08-12 22:53:57,489:INFO:_master_model_container: 9
2023-08-12 22:53:57,489:INFO:_display_container: 2
2023-08-12 22:53:57,489:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=786)
2023-08-12 22:53:57,490:INFO:create_model() successfully completed......................................
2023-08-12 22:53:58,007:INFO:SubProcess create_model() end ==================================
2023-08-12 22:53:58,007:INFO:Creating metrics dataframe
2023-08-12 22:53:58,019:INFO:Initializing Gradient Boosting Classifier
2023-08-12 22:53:58,019:INFO:Total runtime is 0.3650862415631613 minutes
2023-08-12 22:53:58,022:INFO:SubProcess create_model() called ==================================
2023-08-12 22:53:58,023:INFO:Initializing create_model()
2023-08-12 22:53:58,023:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:53:58,023:INFO:Checking exceptions
2023-08-12 22:53:58,023:INFO:Importing libraries
2023-08-12 22:53:58,023:INFO:Copying training dataset
2023-08-12 22:53:58,030:INFO:Defining folds
2023-08-12 22:53:58,030:INFO:Declaring metric variables
2023-08-12 22:53:58,034:INFO:Importing untrained model
2023-08-12 22:53:58,040:INFO:Gradient Boosting Classifier Imported successfully
2023-08-12 22:53:58,051:INFO:Starting cross validation
2023-08-12 22:53:58,052:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:01,050:INFO:Calculating mean and std
2023-08-12 22:54:01,052:INFO:Creating metrics dataframe
2023-08-12 22:54:01,078:INFO:Uploading results into container
2023-08-12 22:54:01,079:INFO:Uploading model into container now
2023-08-12 22:54:01,079:INFO:_master_model_container: 10
2023-08-12 22:54:01,079:INFO:_display_container: 2
2023-08-12 22:54:01,080:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=786, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-12 22:54:01,080:INFO:create_model() successfully completed......................................
2023-08-12 22:54:01,539:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:01,539:INFO:Creating metrics dataframe
2023-08-12 22:54:01,551:INFO:Initializing Linear Discriminant Analysis
2023-08-12 22:54:01,552:INFO:Total runtime is 0.42395964066187547 minutes
2023-08-12 22:54:01,555:INFO:SubProcess create_model() called ==================================
2023-08-12 22:54:01,556:INFO:Initializing create_model()
2023-08-12 22:54:01,556:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:01,556:INFO:Checking exceptions
2023-08-12 22:54:01,556:INFO:Importing libraries
2023-08-12 22:54:01,556:INFO:Copying training dataset
2023-08-12 22:54:01,560:INFO:Defining folds
2023-08-12 22:54:01,561:INFO:Declaring metric variables
2023-08-12 22:54:01,564:INFO:Importing untrained model
2023-08-12 22:54:01,568:INFO:Linear Discriminant Analysis Imported successfully
2023-08-12 22:54:01,576:INFO:Starting cross validation
2023-08-12 22:54:01,578:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:01,717:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:01,733:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:01,834:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:01,843:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:01,915:INFO:Calculating mean and std
2023-08-12 22:54:01,916:INFO:Creating metrics dataframe
2023-08-12 22:54:01,953:INFO:Uploading results into container
2023-08-12 22:54:01,954:INFO:Uploading model into container now
2023-08-12 22:54:01,955:INFO:_master_model_container: 11
2023-08-12 22:54:01,955:INFO:_display_container: 2
2023-08-12 22:54:01,956:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-08-12 22:54:01,956:INFO:create_model() successfully completed......................................
2023-08-12 22:54:02,458:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:02,459:INFO:Creating metrics dataframe
2023-08-12 22:54:02,471:INFO:Initializing Extra Trees Classifier
2023-08-12 22:54:02,472:INFO:Total runtime is 0.43929762442906706 minutes
2023-08-12 22:54:02,481:INFO:SubProcess create_model() called ==================================
2023-08-12 22:54:02,482:INFO:Initializing create_model()
2023-08-12 22:54:02,482:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:02,483:INFO:Checking exceptions
2023-08-12 22:54:02,483:INFO:Importing libraries
2023-08-12 22:54:02,483:INFO:Copying training dataset
2023-08-12 22:54:02,491:INFO:Defining folds
2023-08-12 22:54:02,491:INFO:Declaring metric variables
2023-08-12 22:54:02,495:INFO:Importing untrained model
2023-08-12 22:54:02,501:INFO:Extra Trees Classifier Imported successfully
2023-08-12 22:54:02,518:INFO:Starting cross validation
2023-08-12 22:54:02,524:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:04,743:INFO:Calculating mean and std
2023-08-12 22:54:04,745:INFO:Creating metrics dataframe
2023-08-12 22:54:04,787:INFO:Uploading results into container
2023-08-12 22:54:04,788:INFO:Uploading model into container now
2023-08-12 22:54:04,789:INFO:_master_model_container: 12
2023-08-12 22:54:04,789:INFO:_display_container: 2
2023-08-12 22:54:04,790:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=786, verbose=0, warm_start=False)
2023-08-12 22:54:04,790:INFO:create_model() successfully completed......................................
2023-08-12 22:54:05,307:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:05,307:INFO:Creating metrics dataframe
2023-08-12 22:54:05,341:INFO:Initializing Extreme Gradient Boosting
2023-08-12 22:54:05,342:INFO:Total runtime is 0.48713912169138596 minutes
2023-08-12 22:54:05,350:INFO:SubProcess create_model() called ==================================
2023-08-12 22:54:05,350:INFO:Initializing create_model()
2023-08-12 22:54:05,351:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:05,351:INFO:Checking exceptions
2023-08-12 22:54:05,351:INFO:Importing libraries
2023-08-12 22:54:05,351:INFO:Copying training dataset
2023-08-12 22:54:05,359:INFO:Defining folds
2023-08-12 22:54:05,359:INFO:Declaring metric variables
2023-08-12 22:54:05,364:INFO:Importing untrained model
2023-08-12 22:54:05,370:INFO:Extreme Gradient Boosting Imported successfully
2023-08-12 22:54:05,386:INFO:Starting cross validation
2023-08-12 22:54:05,387:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:07,727:INFO:Calculating mean and std
2023-08-12 22:54:07,729:INFO:Creating metrics dataframe
2023-08-12 22:54:07,770:INFO:Uploading results into container
2023-08-12 22:54:07,771:INFO:Uploading model into container now
2023-08-12 22:54:07,772:INFO:_master_model_container: 13
2023-08-12 22:54:07,772:INFO:_display_container: 2
2023-08-12 22:54:07,774:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)
2023-08-12 22:54:07,774:INFO:create_model() successfully completed......................................
2023-08-12 22:54:08,297:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:08,298:INFO:Creating metrics dataframe
2023-08-12 22:54:08,331:INFO:Initializing Light Gradient Boosting Machine
2023-08-12 22:54:08,331:INFO:Total runtime is 0.5369559526443481 minutes
2023-08-12 22:54:08,339:INFO:SubProcess create_model() called ==================================
2023-08-12 22:54:08,339:INFO:Initializing create_model()
2023-08-12 22:54:08,340:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:08,340:INFO:Checking exceptions
2023-08-12 22:54:08,340:INFO:Importing libraries
2023-08-12 22:54:08,340:INFO:Copying training dataset
2023-08-12 22:54:08,353:INFO:Defining folds
2023-08-12 22:54:08,353:INFO:Declaring metric variables
2023-08-12 22:54:08,360:INFO:Importing untrained model
2023-08-12 22:54:08,368:INFO:Light Gradient Boosting Machine Imported successfully
2023-08-12 22:54:08,380:INFO:Starting cross validation
2023-08-12 22:54:08,382:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:09,877:INFO:Calculating mean and std
2023-08-12 22:54:09,878:INFO:Creating metrics dataframe
2023-08-12 22:54:09,917:INFO:Uploading results into container
2023-08-12 22:54:09,918:INFO:Uploading model into container now
2023-08-12 22:54:09,918:INFO:_master_model_container: 14
2023-08-12 22:54:09,918:INFO:_display_container: 2
2023-08-12 22:54:09,919:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=786, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-08-12 22:54:09,919:INFO:create_model() successfully completed......................................
2023-08-12 22:54:10,522:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:10,522:INFO:Creating metrics dataframe
2023-08-12 22:54:10,538:INFO:Initializing CatBoost Classifier
2023-08-12 22:54:10,538:INFO:Total runtime is 0.5737388610839844 minutes
2023-08-12 22:54:10,545:INFO:SubProcess create_model() called ==================================
2023-08-12 22:54:10,545:INFO:Initializing create_model()
2023-08-12 22:54:10,546:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:10,546:INFO:Checking exceptions
2023-08-12 22:54:10,546:INFO:Importing libraries
2023-08-12 22:54:10,546:INFO:Copying training dataset
2023-08-12 22:54:10,553:INFO:Defining folds
2023-08-12 22:54:10,554:INFO:Declaring metric variables
2023-08-12 22:54:10,561:INFO:Importing untrained model
2023-08-12 22:54:10,569:INFO:CatBoost Classifier Imported successfully
2023-08-12 22:54:10,588:INFO:Starting cross validation
2023-08-12 22:54:10,589:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:17,516:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:


7 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to 0.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 260, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\hites\anaconda3\lib\site-packages\joblib\memory.py", line 655, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\memory.py", line 398, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\memory.py", line 309, in call
    output = self.func(*args, **kwargs)
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 66, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\hites\anaconda3\lib\site-packages\catboost\core.py", line 5131, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\hites\anaconda3\lib\site-packages\catboost\core.py", line 2357, in _fit
    self._train(
  File "C:\Users\hites\anaconda3\lib\site-packages\catboost\core.py", line 1761, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4624, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4673, in _catboost._CatBoost._train
_catboost.CatBoostError: C:/Go_Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info



2023-08-12 22:54:17,517:INFO:Calculating mean and std
2023-08-12 22:54:17,519:INFO:Creating metrics dataframe
2023-08-12 22:54:17,588:INFO:Uploading results into container
2023-08-12 22:54:17,589:INFO:Uploading model into container now
2023-08-12 22:54:17,590:INFO:_master_model_container: 15
2023-08-12 22:54:17,591:INFO:_display_container: 2
2023-08-12 22:54:17,591:INFO:<catboost.core.CatBoostClassifier object at 0x0000023C51ACDEA0>
2023-08-12 22:54:17,591:INFO:create_model() successfully completed......................................
2023-08-12 22:54:18,173:WARNING:create_model() for <catboost.core.CatBoostClassifier object at 0x0000023C51ACDEA0> raised an exception or returned all 0.0, trying without fit_kwargs:
2023-08-12 22:54:18,188:WARNING:Traceback (most recent call last):
  File "C:\Users\hites\anaconda3\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 797, in compare_models
    np.sum(
AssertionError

2023-08-12 22:54:18,190:INFO:Initializing create_model()
2023-08-12 22:54:18,190:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:18,190:INFO:Checking exceptions
2023-08-12 22:54:18,190:INFO:Importing libraries
2023-08-12 22:54:18,190:INFO:Copying training dataset
2023-08-12 22:54:18,201:INFO:Defining folds
2023-08-12 22:54:18,203:INFO:Declaring metric variables
2023-08-12 22:54:18,209:INFO:Importing untrained model
2023-08-12 22:54:18,216:INFO:CatBoost Classifier Imported successfully
2023-08-12 22:54:18,227:INFO:Starting cross validation
2023-08-12 22:54:18,228:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:30,779:INFO:Calculating mean and std
2023-08-12 22:54:30,781:INFO:Creating metrics dataframe
2023-08-12 22:54:30,899:INFO:Uploading results into container
2023-08-12 22:54:30,901:INFO:Uploading model into container now
2023-08-12 22:54:30,902:INFO:_master_model_container: 16
2023-08-12 22:54:30,902:INFO:_display_container: 2
2023-08-12 22:54:30,903:INFO:<catboost.core.CatBoostClassifier object at 0x0000023C51C64760>
2023-08-12 22:54:30,903:INFO:create_model() successfully completed......................................
2023-08-12 22:54:31,467:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:31,467:INFO:Creating metrics dataframe
2023-08-12 22:54:31,499:INFO:Initializing Dummy Classifier
2023-08-12 22:54:31,499:INFO:Total runtime is 0.9230944752693176 minutes
2023-08-12 22:54:31,504:INFO:SubProcess create_model() called ==================================
2023-08-12 22:54:31,505:INFO:Initializing create_model()
2023-08-12 22:54:31,505:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023C520A05B0>, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:31,505:INFO:Checking exceptions
2023-08-12 22:54:31,505:INFO:Importing libraries
2023-08-12 22:54:31,505:INFO:Copying training dataset
2023-08-12 22:54:31,511:INFO:Defining folds
2023-08-12 22:54:31,511:INFO:Declaring metric variables
2023-08-12 22:54:31,515:INFO:Importing untrained model
2023-08-12 22:54:31,519:INFO:Dummy Classifier Imported successfully
2023-08-12 22:54:31,530:INFO:Starting cross validation
2023-08-12 22:54:31,531:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 22:54:31,681:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,682:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,688:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,691:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,701:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,703:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,705:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,712:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,837:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:31,842:WARNING:C:\Users\hites\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-12 22:54:32,082:INFO:Calculating mean and std
2023-08-12 22:54:32,093:INFO:Creating metrics dataframe
2023-08-12 22:54:32,152:INFO:Uploading results into container
2023-08-12 22:54:32,155:INFO:Uploading model into container now
2023-08-12 22:54:32,156:INFO:_master_model_container: 17
2023-08-12 22:54:32,157:INFO:_display_container: 2
2023-08-12 22:54:32,157:INFO:DummyClassifier(constant=None, random_state=786, strategy='prior')
2023-08-12 22:54:32,157:INFO:create_model() successfully completed......................................
2023-08-12 22:54:32,645:INFO:SubProcess create_model() end ==================================
2023-08-12 22:54:32,645:INFO:Creating metrics dataframe
2023-08-12 22:54:32,671:INFO:Initializing create_model()
2023-08-12 22:54:32,671:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=<catboost.core.CatBoostClassifier object at 0x0000023C51C64760>, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-08-12 22:54:32,671:INFO:Checking exceptions
2023-08-12 22:54:32,674:INFO:Importing libraries
2023-08-12 22:54:32,675:INFO:Copying training dataset
2023-08-12 22:54:32,686:INFO:Defining folds
2023-08-12 22:54:32,686:INFO:Declaring metric variables
2023-08-12 22:54:32,687:INFO:Importing untrained model
2023-08-12 22:54:32,687:INFO:Declaring custom model
2023-08-12 22:54:32,687:INFO:CatBoost Classifier Imported successfully
2023-08-12 22:54:32,689:INFO:Cross validation set to False
2023-08-12 22:54:32,689:INFO:Fitting Model
2023-08-12 22:54:36,198:INFO:<catboost.core.CatBoostClassifier object at 0x0000023C520A3C10>
2023-08-12 22:54:36,198:INFO:create_model() successfully completed......................................
2023-08-12 22:54:36,671:INFO:_master_model_container: 17
2023-08-12 22:54:36,673:INFO:_display_container: 2
2023-08-12 22:54:36,673:INFO:<catboost.core.CatBoostClassifier object at 0x0000023C520A3C10>
2023-08-12 22:54:36,673:INFO:compare_models() successfully completed......................................
2023-08-12 23:05:10,739:INFO:Initializing create_model()
2023-08-12 23:05:10,739:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=catboost, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-08-12 23:05:10,739:INFO:Checking exceptions
2023-08-12 23:05:10,779:INFO:Importing libraries
2023-08-12 23:05:10,779:INFO:Copying training dataset
2023-08-12 23:05:10,797:INFO:Defining folds
2023-08-12 23:05:10,797:INFO:Declaring metric variables
2023-08-12 23:05:10,809:INFO:Importing untrained model
2023-08-12 23:05:10,814:INFO:CatBoost Classifier Imported successfully
2023-08-12 23:05:10,821:INFO:Starting cross validation
2023-08-12 23:05:10,823:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-12 23:05:21,751:INFO:Calculating mean and std
2023-08-12 23:05:21,751:INFO:Creating metrics dataframe
2023-08-12 23:05:21,767:INFO:Finalizing model
2023-08-12 23:05:21,908:INFO:Uploading results into container
2023-08-12 23:05:21,908:INFO:Uploading model into container now
2023-08-12 23:05:21,939:INFO:_master_model_container: 18
2023-08-12 23:05:21,939:INFO:_display_container: 3
2023-08-12 23:05:21,939:INFO:<catboost.core.CatBoostClassifier object at 0x0000023C520A26B0>
2023-08-12 23:05:21,939:INFO:create_model() successfully completed......................................
2023-08-12 23:06:13,962:INFO:Initializing predict_model()
2023-08-12 23:06:13,962:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, estimator=<catboost.core.CatBoostClassifier object at 0x0000023C520A26B0>, probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x0000023C5218A3B0>)
2023-08-12 23:06:13,963:INFO:Checking exceptions
2023-08-12 23:06:13,963:INFO:Preloading libraries
2023-08-12 23:06:13,966:INFO:Set up data.
2023-08-12 23:06:13,984:INFO:Set up index.
2023-08-12 23:07:16,932:INFO:Initializing plot_model()
2023-08-12 23:07:16,932:INFO:plot_model(plot=auc, fold=None, verbose=True, display=None, display_format=None, estimator=<catboost.core.CatBoostClassifier object at 0x0000023C520A26B0>, feature_name=None, fit_kwargs=None, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, system=True)
2023-08-12 23:07:16,933:INFO:Checking exceptions
2023-08-12 23:07:16,939:INFO:Preloading libraries
2023-08-12 23:07:16,943:INFO:Copying training dataset
2023-08-12 23:07:16,943:INFO:Plot type: auc
2023-08-12 23:07:17,025:INFO:Fitting Model
2023-08-12 23:07:17,041:INFO:Scoring test/hold-out set
2023-08-12 23:07:17,371:INFO:Visual Rendered Successfully
2023-08-12 23:07:17,809:INFO:plot_model() successfully completed......................................
2023-08-12 23:08:10,126:INFO:Initializing plot_model()
2023-08-12 23:08:10,126:INFO:plot_model(plot=pr, fold=None, verbose=True, display=None, display_format=None, estimator=<catboost.core.CatBoostClassifier object at 0x0000023C520A26B0>, feature_name=None, fit_kwargs=None, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, system=True)
2023-08-12 23:08:10,126:INFO:Checking exceptions
2023-08-12 23:08:10,132:INFO:Preloading libraries
2023-08-12 23:08:10,135:INFO:Copying training dataset
2023-08-12 23:08:10,135:INFO:Plot type: pr
2023-08-12 23:08:10,210:INFO:Fitting Model
2023-08-12 23:08:10,211:INFO:Scoring test/hold-out set
2023-08-12 23:08:10,421:INFO:Visual Rendered Successfully
2023-08-12 23:08:10,899:INFO:plot_model() successfully completed......................................
2023-08-12 23:08:42,462:INFO:Initializing plot_model()
2023-08-12 23:08:42,462:INFO:plot_model(plot=feature, fold=None, verbose=True, display=None, display_format=None, estimator=<catboost.core.CatBoostClassifier object at 0x0000023C520A26B0>, feature_name=None, fit_kwargs=None, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>, system=True)
2023-08-12 23:08:42,462:INFO:Checking exceptions
2023-08-12 23:08:42,468:INFO:Preloading libraries
2023-08-12 23:08:42,471:INFO:Copying training dataset
2023-08-12 23:08:42,473:INFO:Plot type: feature
2023-08-12 23:08:42,473:WARNING:No coef_ found. Trying feature_importances_
2023-08-12 23:08:42,668:INFO:Visual Rendered Successfully
2023-08-12 23:08:43,219:INFO:plot_model() successfully completed......................................
2023-08-12 23:09:17,198:INFO:Initializing interpret_model()
2023-08-12 23:09:17,199:INFO:interpret_model(estimator=<catboost.core.CatBoostClassifier object at 0x0000023C520A26B0>, use_train_data=False, X_new_sample=None, y_new_sample=None, feature=None, kwargs={}, observation=None, plot=summary, save=False, self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023C496D42E0>)
2023-08-12 23:09:17,199:INFO:Checking exceptions
2023-08-12 23:09:17,199:INFO:Soft dependency imported: shap: 0.42.1
2023-08-12 23:09:24,365:INFO:plot type: summary
2023-08-12 23:09:24,365:INFO:Creating TreeExplainer
2023-08-12 23:09:24,457:INFO:Compiling shap values
2023-08-12 23:09:25,446:WARNING:No data for colormapping provided via 'c'. Parameters 'vmin', 'vmax' will be ignored

2023-08-12 23:09:25,855:INFO:Visual Rendered Successfully
2023-08-12 23:09:25,855:INFO:interpret_model() successfully completed......................................
